apiVersion: v1
kind: Service
metadata:
  labels:
    app: sui
  name: sui
spec:
  ports:
    - name: node
      port: 34525
      targetPort: node
  selector:
    app: sui
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: sui
  name: sui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sui
  serviceName: sui
  template:
    metadata:
      labels:
        app: sui
    spec:
      containers:
        - name: sui-node
          image: sui-node
          command:
            - /bin/sh
            - -c
            - /tmp/start_node.sh
          ports:
            - containerPort: 34525
              name: node
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 34525

      restartPolicy: Always
