apiVersion: v1
kind: Service
metadata:
  labels:
    app: sui
  name: sui
spec:
  ports:
    - name: node
      port: 3030
      targetPort: node
  selector:
    app: sui
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: sui
  name: sui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sui
  serviceName: sui
  template:
    metadata:
      labels:
        app: sui
    spec:
      containers:
        - name: sui-node
          image: sui-node
          command:
            - /bin/sh
            - -c
            - /tmp/start_node.sh
          ports:
            - containerPort: 3030
              name: node
              protocol: TCP
            - containerPort: 3031
              name: webserver
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 3030
        - name: sui-contracts
          image: sui-contracts
          command:
            - /bin/sh
            - -c
            - "sh devnet_deploy.sh && touch success && sleep infinity"
          readinessProbe:
            tcpSocket:
              port: 3030
            periodSeconds: 1
            initialDelaySeconds: 15
            periodSeconds: 5

      restartPolicy: Always
